### ISSUE TITLE
H5ls analogous behavior ?

### ISSUE THREAD

**Issue by k3yavi** [aldanor/hdf5-rust#58] opened 2019-09-03 04:15 UTC
Hi @aldanor ,

Thanks for the awesome library.
I am using the library for one of small project [here](https://github.com/COMBINE-lab/EDS). The use case I am looking for is analogous to h5ls i.e. I want to know the group names present in the file before extracting the datatset. Is it possible to share a small example which queries the h5 for group name and select a group and load the data from the group into a u32 vector ? I tried using fapl to extract the properties of the file but the program gives compilation error.

While poking I also found that as the example in the readme somehow hdf5::File::create command doesn't compiles but works when I do hdf5::File::open. Also open command always expects to have 2 parameters even if I want to open the file in just read only mode. I was looking at the code [here](https://github.com/aldanor/hdf5-rust/blob/master/src/hl/file.rs) but couldn't understand which code path actually is being followed for opening a file. 

Thanks again.

**Comment by aldanor** [comment] 2019-09-03 09:23
Hi @k3yavi - happy to help, but could you post some code examples? In particular, the ones that don’t compile. It would be easier to see if something’s wrong.

In regards to checking the contents of the group, would this help? https://github.com/aldanor/hdf5-rust/blob/master/src/hl/group.rs#L175

**Comment by aldanor** [comment] 2019-09-03 09:29
You can see all of the File constructors here btw:

https://github.com/aldanor/hdf5-rust/blob/master/src/hl/file.rs#L74

**Comment by k3yavi** [comment] 2019-09-03 17:32
Hi @aldanor ,

Thanks for the prompt reply and my apologies in advance if my question are naive to start with.
Basically I have an h5 file which when viewed with `h5ls` looks like as follows:
```
╰─$ /home/linuxbrew/.linuxbrew/bin/h5ls -r quants_mat.h5

/                        Group
/matrix                  Group
/features                Group
/matrix/data             Dataset {3121051}
```

My use case is to first programmatically query the `h5` (something like h5ls above), figure out which _group_ has the `data` h5 Dataset, for example `matrix` group above has data but the group name `matrix` is not mandatory, and later retrieve the `/<GROUP>/data` into a rust vector.

I started playing with the library and have a small snippet with cargo entry `hdf5 = "0.5.2"` as follows:
```
extern crate hdf5;

fn main() {
    1. //let file = hdf5::File::open( "/home/quants_mat.h5" )
    //    .expect("can't create output file");

    2. let file = hdf5::File::open( "/home/quants_mat.h5", "r" )
        .expect("can't create output file");

    3. //let fp = file.fapl();

    4. //let file = hdf5::File::create("pixels.h5").unwrap();

}
```

I numbered the lines in the code to point. The 1 line (if uncommented) gives the following error:
```
error[E0061]: this function takes 2 parameters but 1 parameter was supplied
 --> src/main.rs:4:16
  |
4 |     let file = hdf5::File::open( "/home/quants_mat.h5" )
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 2 parameters

error: aborting due to previous error

For more information about this error, try `rustc --explain E0061`
```
I basically wanted to open the file as read only (like `let file = hdf5::File::open("pixels.h5")?;` in the READme example), I could get away with using 2 by explicitly providing the `r`. However, when I went to the [link](https://github.com/aldanor/hdf5-rust/blob/master/src/hl/file.rs#L74) with the file constructors I can find open function with one parameter which makes me wonder am I looking at the right code path ? Similarly 3 gave me following error, even though the file object does have [this](https://github.com/aldanor/hdf5-rust/blob/master/src/hl/file.rs#L182) method.

```
error[E0599]: no method named `fapl` found for type `hdf5::File` in the current scope
  --> src/main.rs:12:19
   |
12 |     let fp = file.fapl();
   |                   ^^^^

error: aborting due to previous error
```

Similarly 4 gives me following error:
```
error[E0599]: no function or associated item named `create` found for type `hdf5::File` in the current scope
  --> src/main.rs:13:28
   |
13 |     let file = hdf5::File::create("pixels.h5").unwrap();
   |                            ^^^^^^ function or associated item not found in `hdf5::File`

error: aborting due to previous error
```

In _summary_  I can make the `h5` writing work for my use case [here](https://github.com/COMBINE-lab/EDS/blob/master/src-rs/src/h5.rs#L11)  but I question my understanding of the library given the questions above, I don't have answer for, when reading a `h5` file. I still have to figure out, once I can query the groups how to load a dataset into a rust vector.

It'd be great to have a couple of more examples for reading / writing the h5 file in the library. I'd be happy to help too, in that regards.

**Comment by aldanor** [comment] 2019-09-04 11:32
Ah, I see. It's simple: the docs are based on the master branch which has diverged from the 0.5.2 release. If you use `{ git = "https://github.com/aldanor/hdf5-rust.git", rev = "e7a28a7" }`, things should work as intended.

Maybe I should release the v0.6.0 (will try to, tonight). I was planning to hold off on it because I have lots of stuff implemented locally that I wanted to bring in before that - but it will take some time, so maybe it's best to push a stable version for now which will be in sync with the docs.

**Comment by aldanor** [comment] 2019-09-04 11:34
> My use case is to first programmatically query the h5 (something like h5ls above), figure out which group has the data h5 Dataset, for example matrix group above has data but the group name matrix is not mandatory, and later retrieve the /<GROUP>/data into a rust vector.

In regards to group names, again, you don't need `fapl()`, you probably need `member_names()` which works for both File and Group and returns a list of names of immediate child objects.

**Comment by k3yavi** [comment] 2019-09-04 16:11
Awesome ! Thanks for the help @aldanor . I'll check it soon and will update it here.

**Comment by aldanor** [comment] 2019-10-04 20:38
Closing since it seems to have worked.

**Closed by aldanor** 2019-10-04 20:38 UTC

**Comment by k3yavi** [comment] 2019-10-04 22:41
Thanks @aldnor, it looks great. My apologies for not closing it earlier.
